[tool.poetry]
name = "node_helpers"
version = "1.0.0"
description = "An opinionated ROS2 framework that minimizes boilerplate while maximizing reliability. Features intuitive APIs for parameter management, action handling, and error-resilient RPC. Designed by Urban Machine for safe and scalable robotics."
authors = ["urbanmachine <alex@urbanmachine.build>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.12.0"
PyYAML = "^6.0"
pydantic = "^2.5.2"
numpy = "<2.0.0"  # 2.0.0 should be supported after Jazzy upgrade

[tool.poetry.scripts]
interactive_transform_publisher = "node_helpers.nodes.interactive_transform_publisher:main"
sound_player = "node_helpers.nodes.sound_player:main"
placeholder = "node_helpers.nodes.placeholder:main"

[tool.colcon-poetry-ros.data-files]
"share/ament_index/resource_index/packages" = ["resource/node_helpers"]
"share/node_helpers" = ["package.xml"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"