[tool.poetry]
name = "node_helpers"
version = "1.0.0"
description = "An opinionated ROS2 framework that minimizes boilerplate while maximizing reliability. Features intuitive APIs for parameter management, action handling, and error-resilient RPC. Designed by Urban Machine for safe and scalable robotics."
authors = ["urbanmachine <alex@urbanmachine.build>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.12.0,<4.0"
numpy = "^2.1.3"
pydantic = "^2.10.1"
pyyaml = "^6.0.2"

# For ros2_numpy, this brings in a newer version of transforms3d that has been updated
# to work with numpy 2.0.0+
transforms3d = "^0.4.2"

[tool.poetry.scripts]
interactive_transform_publisher = "node_helpers.nodes.interactive_transform_publisher:main"
sound_player = "node_helpers.nodes.sound_player:main"
placeholder = "node_helpers.nodes.placeholder:main"

[tool.colcon-poetry-ros.data-files]
"share/ament_index/resource_index/packages" = ["resource/node_helpers"]
"share/node_helpers" = ["package.xml", "sample_urdfs/"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"